steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/ui-service:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '--cache-from', 'gcr.io/$PROJECT_ID/ui-service:latest',
          '-t', 'gcr.io/$PROJECT_ID/ui-service:latest', 
          '-f', 'devops/Dockerfile', 
          '.'
        ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/ui-service:latest"]
- name: 'gcr.io/cloud-builders/gcloud-slim'
  args: [
          'compute', 'ssh', 'instance-1',
          '--zone=us-central1-a',
          '--command=
            date;
          '
        ]
images: ['gcr.io/$PROJECT_ID/ui-service:latest']
